 insert into report ([report],[language],[field],[value]) values 
 ('loan','chi','receiver',N'致：威爾斯親王醫院 坐姿綜合診所')
 ,('loan','chi','formNo',N'編號：' )
 ,('loan','chi','loanLetterTitle',N'借用輪椅及附件保証書' )
 ,('loan','chi','adaptivePartsSectionTitle',N'附件:' )
 ,('loan','chi','adaptivePartsSection_ArticleNo','Article No' )
 ,('loan','chi','adaptivePartsSection_Description','Description' )
 ,('loan','chi','adaptivePartsSection_Price','Ref. Price' )
 ,('loan','chi','adaptivePartsSection_Remarks','Remarks' )
 ,('loan','chi','depositeAgree','' )
 ,('loan','chi','agreement',N'本人明白該輪椅及附件之借用期為㇐年，如須續借，應於會診後重新辦理續借手續。該輪椅及附 件乃威爾斯親王醫院國泰愛心兒童輪椅庫所擁有，而坐姿綜合診所會負起輪椅正常維修之責任。 本人同意承擔輪椅損壞及遺失之責任（包括正常耗損及更換配件所需之費用）。' )
 ,('loan','chi','guardianDate',N'日期：' )
 ,('loan','chi','guardianSignature',N'監護人簽署：' )
 ,('loan','chi','witness',N'見証人：' )
 ,('loan','chi','witnessSignature',N'簽署：' )
 ,('loan','chi','returnDate',N'退還日期：' )
 ,('loan','chi','footerNotes',N'注意事項:' )
 ,('loan','chi','loanLetter_sec1_1stLine',N'本人 @BorrowerName （身份證號碼） @Idno' )
 ,('loan','chi','loanLetter_sec1_Residing',N'現居' )
 ,('loan','chi','loanLetter_sec1_Telephone',N'電話' )
 ,('loan','chi','loanLetter_sec1_Guardian',N'乃' )
 ,('loan','chi','loanLetter_sec1_receive',N'之家⾧／監護人現向威爾斯親王醫院國泰愛心兒童輪椅庫借用輪椅及其附件 ，其資料如下：' )
 ,('loan','chi','loanLetter_sec1_detail',N'' )
 ,('loan','chi','loanLetter_sec1_wcDetail',N'輪椅號碼及種類：' )
 ,('loan_note','chi','1',N'應經常檢查輪胎是否有充足的空氣。' )
 ,('loan_note','chi','2',N'用乾布將弄濕的位置抺乾。' )
 ,('loan_note','chi','3',N'每㇐至二星期使用潤滑機油為輪椅的車輪軸及其它轉動部份或零件唧油。' )
 ,('loan_note','chi','4',N'請於每星期、覆診前及歸還輪椅前為輪椅及其附件清潔乾淨，保持衞生。' )
 ,('loan_note','chi','5',N'於借用期間，輪椅及其附件如有任何問題，請盡快與坐姿診所職員聯絡，電話：26321240' );